FROM openjdk:17-jdk-slim-buster
WORKDIR /backend
COPY gradlew .
COPY gradle gradle
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar
EXPOSE 8080

ARG JAR_FILE=/backend/build/libs/whiskeywiki-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","/app.jar"]
VOLUME /tmp