FROM openjdk:17-jdk-slim-buster AS builder
WORKDIR /backend
COPY gradlew .
COPY gradle gradle
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar
FROM openjdk:17-jdk-slim-buster
COPY --from=builder backend/build/libs/*.jar app.jar

ENTRYPOINT ["java","-Dspring.profiles.active=prod", "-jar", "/app.jar"]
VOLUME /tmp
