spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://whiskeywiki.shop:3307/test_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: b101

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      host: whiskeywiki.shop
      port: 6380