# DB 설정
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/whiskey
    username: admin
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      path: /h2console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none