# DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PROD_PORT}/whiskeywikiDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      host: ${REDIS_HOST}
      port: ${REDIS_PROD_PORT}